import fs from 'node:fs';
import path from 'node:path';

const PLACEHOLDERS = [
  '[Project Name]',
  '[Brief description]',
  '[web-app | api | cli-tool | library | mobile-app | other]',
  '[Language / Framework / Database / etc.]',
];

/**
 * Parse project identity fields from CLAUDE.md.
 * Returns null for fields that still have placeholder values or are missing.
 *
 * @param {string} projectDir
 * @returns {{ name: string|null, description: string|null, type: string|null, stack: string|null }}
 */
export function parseProjectIdentity(projectDir) {
  const claudeMdPath = path.join(projectDir, 'CLAUDE.md');
  const identity = { name: null, description: null, type: null, stack: null };

  if (!fs.existsSync(claudeMdPath)) {
    return identity;
  }

  const content = fs.readFileSync(claudeMdPath, 'utf-8');

  const patterns = [
    { key: 'name', regex: /\*\*Project:\*\*\s*(.+)/ },
    { key: 'description', regex: /\*\*Description:\*\*\s*(.+)/ },
    { key: 'type', regex: /\*\*Type:\*\*\s*(.+)/ },
    { key: 'stack', regex: /\*\*Stack:\*\*\s*(.+)/ },
  ];

  for (const { key, regex } of patterns) {
    const match = content.match(regex);
    if (match) {
      const value = match[1].trim();
      if (!PLACEHOLDERS.includes(value)) {
        identity[key] = value;
      }
    }
  }

  return identity;
}

/**
 * Discover active rules from .claude/rules/.
 * Returns objects with file name and title (first H1 heading).
 * Excludes README.md.
 *
 * @param {string} projectDir
 * @returns {{ file: string, title: string }[]}
 */
export function discoverRules(projectDir) {
  const rulesDir = path.join(projectDir, '.claude', 'rules');
  if (!fs.existsSync(rulesDir)) {
    return [];
  }

  const files = fs.readdirSync(rulesDir, { withFileTypes: true })
    .filter(entry => entry.isFile() && entry.name.endsWith('.md') && entry.name !== 'README.md')
    .map(entry => entry.name)
    .sort();

  return files.map(file => {
    const content = fs.readFileSync(path.join(rulesDir, file), 'utf-8');
    const headingMatch = content.match(/^#\s+(.+)/m);
    const title = headingMatch ? headingMatch[1].trim() : file.replace('.md', '');
    return { file, title };
  });
}

/**
 * Discover available commands from .claude/commands/.
 * Returns objects with slash command name and title.
 *
 * @param {string} projectDir
 * @returns {{ name: string, title: string, file: string }[]}
 */
export function discoverCommands(projectDir) {
  const cmdsDir = path.join(projectDir, '.claude', 'commands');
  if (!fs.existsSync(cmdsDir)) {
    return [];
  }

  const files = fs.readdirSync(cmdsDir, { withFileTypes: true })
    .filter(entry => entry.isFile() && entry.name.endsWith('.md'))
    .map(entry => entry.name)
    .sort();

  return files.map(file => {
    const content = fs.readFileSync(path.join(cmdsDir, file), 'utf-8');
    const name = '/' + file.replace('.md', '');

    // Try to extract title from "# /command-name - Title" pattern
    const headingMatch = content.match(/^#\s+\/[\w-]+\s*[-—]\s*(.+)/m);
    const title = headingMatch ? headingMatch[1].trim() : name;

    return { name, file, title };
  });
}

/**
 * Generate AGENTS.md content from the project's governance files.
 *
 * @param {string} projectDir
 * @returns {string}
 */
export function generateAgentsMd(projectDir) {
  const identity = parseProjectIdentity(projectDir);
  const rules = discoverRules(projectDir);
  const commands = discoverCommands(projectDir);

  const sections = [];

  // Header
  if (identity.name) {
    sections.push(`# AGENTS.md — ${identity.name}`);
  } else {
    sections.push('# AGENTS.md');
  }

  sections.push('');
  sections.push('> Generated by [AIAgentMinder](https://github.com/lwalden/AIAgentMinder). Do not edit manually — regenerate with `npx aiagentminder agents-md`.');
  sections.push('');

  // Project overview
  if (identity.name || identity.description || identity.stack) {
    sections.push('## Project Overview');
    sections.push('');
    if (identity.description) {
      sections.push(identity.description);
      sections.push('');
    }
    if (identity.type) {
      sections.push(`- **Type:** ${identity.type}`);
    }
    if (identity.stack) {
      sections.push(`- **Stack:** ${identity.stack}`);
    }
    sections.push('');
  }

  // Coding conventions (from rules)
  if (rules.length > 0) {
    sections.push('## Coding Conventions');
    sections.push('');
    sections.push('This project uses AIAgentMinder governance rules, loaded automatically from `.claude/rules/`:');
    sections.push('');

    for (const rule of rules) {
      sections.push(`- **${rule.title}** (\`.claude/rules/${rule.file}\`)`);
    }
    sections.push('');

    // Extract key conventions from well-known rules
    const conventions = extractConventions(rules);
    if (conventions.length > 0) {
      sections.push('### Key Conventions');
      sections.push('');
      for (const conv of conventions) {
        sections.push(`- ${conv}`);
      }
      sections.push('');
    }
  }

  // Commands
  if (commands.length > 0) {
    sections.push('## Available Commands');
    sections.push('');
    sections.push('These slash commands are available in Claude Code sessions:');
    sections.push('');

    for (const cmd of commands) {
      sections.push(`- \`${cmd.name}\` — ${cmd.title}`);
    }
    sections.push('');
  }

  // Architecture decisions
  const decisionsPath = path.join(projectDir, 'DECISIONS.md');
  if (fs.existsSync(decisionsPath)) {
    sections.push('## Architecture Decisions');
    sections.push('');
    sections.push('Significant architectural decisions are recorded in `DECISIONS.md`. Consult it before making changes to established patterns.');
    sections.push('');
  }

  return sections.join('\n') + '\n';
}

/**
 * Extract key coding conventions from well-known rule files.
 */
function extractConventions(rules) {
  const conventions = [];
  const ruleFiles = new Set(rules.map(r => r.file));

  if (ruleFiles.has('git-workflow.md')) {
    conventions.push('Never commit directly to `main` — use feature branches');
    conventions.push('Commit messages: `type(scope): description` format');
    conventions.push('All changes go through pull requests');
  }

  if (ruleFiles.has('code-quality.md')) {
    conventions.push('TDD: write failing tests first, then implement');
    conventions.push('Run full test suite before every commit');
  }

  if (ruleFiles.has('approach-first.md')) {
    conventions.push('State your approach before implementing architecture changes or multi-file refactors');
  }

  if (ruleFiles.has('architecture-fitness.md')) {
    conventions.push('Flag source files exceeding 300 lines for decomposition');
    conventions.push('No hardcoded credentials in source files');
    conventions.push('External HTTP/DB calls belong in dedicated service modules');
  }

  return conventions;
}

/**
 * Write AGENTS.md to the target directory.
 *
 * @param {string} projectDir
 * @param {{ force?: boolean }} [options]
 * @returns {{ status: 'created'|'skipped', path: string }}
 */
export function writeAgentsMd(projectDir, options = {}) {
  const { force = false } = options;
  const outputPath = path.join(projectDir, 'AGENTS.md');

  if (!force && fs.existsSync(outputPath)) {
    return { status: 'skipped', path: outputPath };
  }

  const content = generateAgentsMd(projectDir);
  fs.writeFileSync(outputPath, content, 'utf-8');

  return { status: 'created', path: outputPath };
}
